version: 2
updates:
  - package-ecosystem: npm
    directory: /code-review-bot
    schedule:
      interval: weekly
    groups:
      compatible-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 5
